Repository thoth-station/helm-charts, pull requests merged in 2022-02, with the labels that each got.

#26 Release often
  .github/workflows/release.yml
  charts/index.yaml
  charts/meteor-pipelines/Chart.yaml
  charts/meteor-pipelines/index.yaml
Labels: size/M, approved

#27 Only install podman and oc when chart testing is needed
  .github/workflows/lint.yml
  .gitignore
  e2e-test.sh
Labels: lgtm, size/M, approved

#23 feat(byon): Import container image pipeline
  charts/meteor-pipelines/Chart.yaml
  charts/meteor-pipelines/templates/byon-import-jupyterhub-image.yaml
  charts/meteor-pipelines/templates/byon-validate-jupyterhub-image.yaml
Labels: size/L, approved
