Repository thoth-station/helm-charts, pull requests merged in 2022-03, with the labels that each got.

#32 enabling tls-verify
  charts/meteor-pipelines/Chart.yaml
  charts/meteor-pipelines/templates/gather-deployment-metrics-pipeline.yaml
  charts/meteor-pipelines/templates/git-issue-template.yaml
  charts/meteor-pipelines/templates/git-model-template.yaml
  charts/meteor-pipelines/templates/issue-pipeline.yaml
  charts/meteor-pipelines/templates/issue-pulp-pypi-release-task.yaml
  charts/meteor-pipelines/templates/issue-pypi-release-task.yaml
  charts/meteor-pipelines/templates/issue-release-task.yaml
  charts/meteor-pipelines/templates/meteor_buildah.yaml
  charts/meteor-pipelines/templates/overlay-build-task.yaml
  charts/meteor-pipelines/templates/overlays-pipeline.yaml
  charts/meteor-pipelines/templates/overlays-release-pipeline.yaml
  charts/meteor-pipelines/templates/pr-build-release.yaml
  charts/meteor-pipelines/templates/pr-build.yaml
  charts/meteor-pipelines/templates/pull-request-pipeline.yaml
  charts/meteor-pipelines/templates/tag-build.yaml
  charts/meteor-pipelines/templates/tag-release-pipeline.yaml
  charts/meteor-pipelines/templates/tag-release-task.yaml
  charts/meteor-pipelines/templates/upload-pulp-pypi.yaml
  charts/meteor-pipelines/templates/upload-pypi.yaml
Labels: size/L, approved

#36 Workaround for flaky CI
  .github/workflows/lint.yml
  e2e-test.sh
Labels: lgtm, size/XS, approved

#34 feat(byon): Minimal image validation
  charts/meteor-pipelines/Chart.yaml
  charts/meteor-pipelines/templates/byon-validate-jupyterhub-image.yaml
Labels: size/L, approved

#37 Remove the needs-triage label from the issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/XS, approved

#35 Fix annotations
  charts/meteor-pipelines/Chart.yaml
  charts/meteor-pipelines/templates/byon-import-jupyterhub-image.yaml
  charts/meteor-pipelines/templates/byon-validate-jupyterhub-image.yaml
Labels: size/S, lgtm, approved
